### ISSUE TITLE
如何自动根据标题提取sidebar

### ISSUE THREAD

**Issue by didoee** [dewfall123/vfc#10]

**Comment by didoee** [comment]
如何自动根据标题提取sidebar

**Comment by dewfall123** [comment]
你指的应该是 vitepress 右侧自动生成的 outline?   https://vitepress.vuejs.org/config/theme-configs#outline
outline 默认开启的

**Comment by didoee** [comment]
不是，自动提取md的标题作为左侧的sidebar，因为每个页面的标题太多，要自己完成的话就太麻烦了
![image](https://user-images.githubusercontent.com/112919246/188851267-7b036c9b-312d-46a7-b693-1116633a60de.png)

**Comment by dewfall123** [comment]
左侧sidebar是配置的
图片里的源码在这里 https://github.com/vuejs/vitepress/blob/main/docs/.vitepress/config.ts#L136
