### ISSUE TITLE
copy 的代码是经过转码的

### ISSUE THREAD

**Issue by Braveheartforyou** [dewfall123/vfc#16]
copy 出来的代码是 经过转码的 %3Ctemplate%3E%0A%20%20%3Cdiv%3E%0A%20%20%20%20%3CScTabs%20%3E%0A%20%20%20%20%20%20%3CTabPane%20key%3D%221%22%20tab%3D%22Tab%201%22%20style%3D%22height%3A%20200px%22%3EContent%20of%20Tab%20Pane%201%3C%2FTabPane%3E%0A%20%20%20%20%20%20%3CTabPane%20key%3D%222%22%20tab%3D%22Tab%202%22%20style%3D%22height%3A%20200px%22%3EContent%20of%20Tab%20Pane%202%3C%2FTabPane%3E%0A%20%20%20%20%3C%2FScTabs%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Ftemplate%3E%0A%0A%3Cscript%20setup%20lang%3D%22ts%22%3E%0Aimport%20%7B%20TabPane%20%7D%20from%20'ant-design-vue'%0Aimport%20%7B%20ScTabs%20%7D%20from%20'sc-ui'%0Aimport%20%22ant-design-vue%2Fdist%2Fantd.css%22%0A%3C%2Fscript%3E%0A%0A%3Cstyle%20lang%3D%22less%22%3E%0A%3C%2Fstyle%3E

**Comment by kcmeven** [comment]
+1

**Comment by ckangwen** [comment]
v0.2.9是没问题的，v0.2.8确实有问题

**Comment by dewfall123** [comment]
#13 已经修复了
