### ISSUE TITLE
生成的demo-*.vue文件是否能自动删除

### ISSUE THREAD

**Issue by yue7872** [dewfall123/vfc#18]
md-demo-plugins插件会在markdown目录下自动生成`demo-1.vue`文件
看起来不会自动删除
https://github.com/dewfall123/ruabick/blob/a8f9312cb71d7b651093bc3e4d8750b26b69d85d/packages/md-demo-plugins/src/utils.ts#L56

如果自动删除不好实现，是否考虑将生成的文件放在temp或者dist文件夹里，方便管理

**Comment by yue7872** [comment]
<img width="259" alt="demo" src="https://user-images.githubusercontent.com/22944518/200559375-2e200b6f-ed44-43d0-8417-13fe17a6d2a4.png">

编辑完markdown之后发现多了100多个demo-*.vue 文件

**Comment by dewfall123** [comment]
生成的文件是在`.docs`目录下吧   这个目录应该设置成`ignore`的，和`dist`一样的性质，所以没啥影响吧。

**Comment by yue7872** [comment]
不是的，生成的和原本的文件混在一起，我的目录结构：
```
docs
├── .vitepress
├── common
│ ├── index.md  // 我的markdown文件

│ ├── // 以下是生成的文件
│ ├── demo-1.vue
│ ├── demo-2.vue
│ ├── demo-*.vue...
```

可以加个dist目录吗，这样目录结构不会那么混乱，也便于管理，提个了[PR](https://github.com/dewfall123/ruabick/pull/17)

@dewfall123

**Comment by dewfall123** [comment]
> ```
> docs
> ├── .vitepress
> ├── common
> │ ├── index.md  // 我的markdown文件
> 
> │ ├── // 以下是生成的文件
> │ ├── demo-1.vue
> │ ├── demo-2.vue
> │ ├── demo-*.vue...
> ```
我用这个目录不能复现。是不是你不是用脚手架配置生成的项目，配置和命令不对导致的？
https://github.com/dewfall123/ruabick/tree/master/packages/vite-plugin-gen-temp#%E6%AD%A5%E9%AA%A4-2

最好能提供复现仓库。

**Comment by dewfall123** [comment]
重复生成demo文件是有问题 （md fence）

**Comment by yue7872** [comment]
@dewfall123 复现仓库：https://github.com/yue7872/vitepress-demo/

用的是这两个插件 `@ruabick/md-demo-plugins`  `@ruabick/vitepress-demo-block`

使用这种形式渲染demo会出现重复生成的问题
```
\```vue:demo
	...vue组件
\```
```

地址：https://github.com/yue7872/vitepress-demo/blob/4d32f3ccd309cdcd635aad5afb99db9ca9666ab6/docs/common/demo.md?plain=1#L26
