### ISSUE TITLE
yarn create @ruabick/vlib 打包问题

### ISSUE THREAD

**Issue by qinggezhenhao** [dewfall123/vfc#8]
vite 配置文件 external: ['vue', ...(packageJson.dependencies || {}), ...(packageJson.peerDependencies || {})]
packageJson 下的这两个key值不存在 打包报错， 去掉的话 打包成功 但是文件夹里没有html。。  这应该怎么部署到服务器上

**Comment by dewfall123** [comment]
`build` 是打包src源码的
`site:build` 才是打包文档站点的  打包的产物会在`.docs\.vitepress\dist`目录

**Comment by dewfall123** [comment]
> packageJson 下的这两个key值不存在 打包报错

感谢提醒，我改下这个

**Comment by qinggezhenhao** [comment]
好的，楼主早。

**Comment by qinggezhenhao** [comment]
好的，楼主早。 还想问下那个 vue文件里 加上lang=‘ts’ 引用 声明的@/xxx 方式 报错 能优化吗～，要是能@/ 出来相对的文件夹路径提示就好了

**Comment by dewfall123** [comment]
> 要是能@/ 出来相对的文件夹路径提示

智能提示是编辑器插件的问题，插件是读的项目文件配置，模板tsconfig配置有点问题

改下`tsconfig.json`文件
```
    "include": [
        "src/index.ts"  // 改成"src/*"
    ],
```

**Comment by qinggezhenhao** [comment]
好的 我试一下 谢谢
